---
- name: Setup external Prerequisites
  include: prepare.yml

- name: Prepare OpenShift nodes
  hosts: OSEv3
  roles:
  - openshift_prepare

- name: Install OS
  include: ../git/openshift-ansible/playbooks/byo/config.yml

- name: Post-Install steps
  include: post_install.yml

