---
- name: OpenShift Post Install steps
  hosts: oo_first_master
  roles:
  - role: openshift_postinstall

- name: Post Install steps
  hosts: nfs
  roles:
  - role: ../git/openshift-ansible/roles/kube_nfs_volumes
    openshift:
      common:
        is_containerized: False
    disks: "/dev/vdb"
    sizes: 1G:5,2G:5,5G:1
    force: no
    validate_certs: False
    kubernetes_url: "{{ openshift_master_api_url }}"
    kubernetes_token: tJdce6Fn3cL1112YoIJ5m2exzAbzcPZX
