---
#- name: Install katello-ca-consumer package
#  yum:
#    name: "https://{{ subscription.hostname }}/pub/katello-ca-consumer-latest.no.arch.rpm"
#    state: installed

- name: Register System with Red Hat
  redhat_subscription:
    state: present
    username: "{{ subscription.username }}"
    password: "{{ subscription.password }}"
    server_proxy_hostname: "{{ proxy.hostname }}"
    server_proxy_port: "{{ proxy.port }}"
    server_proxy_user: "{{ proxy.username }}"
    server_proxy_password: "{{ proxy.password }}"
 #   activationkey: "{{ subscription.activationkey }}"
 #   org_id: "{{ subscription.organization }}"
    pool: '.*OpenShift.*'
  when: subscription.username | bool

- name: Enable RHEL Repositories
  redhat_repositories:
    state: enabled
    id: "{{ repos.rhel }}"
  when: ansible_distribution == "RedHat"

- name: install packages
  yum:
    name:
    - yum-utils
    - createrepo
    - docker
    - git 
    state: installed

- name: repo directory
  file: 
    path: "{{ rpm_repos_dir }}"
    state: directory
    mode: 0777

- name: clone repos
  shell: reposync --gpgcheck -lm --repoid={{ item }} --download_path={{ rpm_repos_dir }}; createrepo -v {{ rpm_repos_dir }}/{{ item }} -o {{ rpm_repos_dir }}/{{ item }}
  args:
    creates: "{{ rpm_repos_dir }}/{{ item }}"
  with_items: "{{ repos.rhel }}"
